# Generated by Django 5.2.7 on 2026-02-12 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('trainer', models.CharField(blank=True, max_length=200, null=True)),
                ('script', models.TextField()),
                ('layout', models.CharField(choices=[('one-photo', 'One Photo'), ('two-photos', 'Two Photos'), ('three-photos', 'Three Photos'), ('circle-photo', 'Circle Photo'), ('grid', 'Grid')], default='one-photo', max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activities/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('transform_style', models.CharField(blank=True, help_text="CSS transform like 'scale(1.1)' or 'translateY(5%)'", max_length=200, null=True)),
                ('object_fit', models.CharField(blank=True, choices=[('contain', 'Contain'), ('cover', 'Cover')], default='cover', max_length=50, null=True)),
                ('background_color', models.CharField(blank=True, help_text="Background color like '#fff' or 'white'", max_length=20, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='activities.activity')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
