# Generated by Django 5.2.7 on 2026-02-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Recruitment', 'Recruitment'), ('Event', 'Event'), ('Policy', 'Policy'), ('General', 'General'), ('Urgent', 'Urgent')], default='General', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archive', 'Archive')], default='active', max_length=20)),
                ('content', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('link_text', models.CharField(default='Take Action →', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-status', 'order', '-date'],
            },
        ),
    ]
