# Generated by Django 5.2.7 on 2026-02-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(),
        ),
    ]
