# Generated by Django 5.2.7 on 2026-02-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('vip', 'VIP Platinum'), ('facebook', 'Facebook Media'), ('instagram', 'Instagram Network')], default='instagram', max_length=50)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(upload_to='sponsors/')),
                ('order', models.IntegerField(default=0)),
                ('transform_style', models.CharField(blank=True, default='scale(1.0)', help_text="CSS transform like 'scale(1.1) translateY(5%)'", max_length=200, null=True)),
                ('object_fit', models.CharField(blank=True, choices=[('contain', 'Contain'), ('cover', 'Cover')], default='cover', max_length=50, null=True)),
                ('object_position', models.CharField(blank=True, default='center', help_text="CSS object-position like 'center', 'top', 'bottom'", max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['type', 'order', '-created_at'],
            },
        ),
    ]
