# Generated by Django 5.2.7 on 2026-02-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='home/activities/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Welcome To MoQawill', max_length=200)),
                ('hero_subtitle', models.CharField(default='Learn here, lead anywhere', max_length=300)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('about_text', models.TextField(blank=True)),
                ('contact_email', models.EmailField(default='moqawillesmt@gmail.com', max_length=254)),
                ('contact_location', models.CharField(default='ESM, Tlemcen, Algeria', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutSection',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='HeroSection',
        ),
    ]
