# Generated by Django 5.2.7 on 2026-02-18 01:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homeactivity_homecontent_delete_aboutsection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeactivity',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='hero_image'),
        ),
    ]
