# Generated by Django 5.2.7 on 2026-02-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Driven by Ambition', max_length=200)),
                ('subtitle', models.CharField(default='Shaping the next generation of ESM leaders since 2020.', max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/hero/')),
            ],
        ),
        migrations.CreateModel(
            name='AboutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='Our Journey', max_length=100)),
                ('title', models.CharField(default='The Legacy of MoQawill', max_length=200)),
                ('paragraph1', models.TextField()),
                ('paragraph2', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/history/')),
            ],
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('president', 'President'), ('vice_president', 'Vice President'), ('supervisor', 'General Supervisor'), ('other', 'Other')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('role_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='about/board/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
