# Generated by Django 5.2.7 on 2026-02-14 22:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_abouthero_image_alter_abouthistory_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
